/**
 * Source for the per-run `<runDir>/.bin/handoff.mjs` helper script.
 *
 * The script is generated once per run, embeds the schema map for every
 * schema-bound prompt step in the flow, and is invoked by the model from inside
 * a single Claude invocation to validate-and-atomically-write its draft handoff
 * JSON. It is intentionally dependency-free so it can run from a temp dir
 * without the relay package being installed there.
 */

/**
 * Body of the helper script. Three placeholder markers are replaced at render
 * time with JSON literals — JSON syntax is a subset of JS object/string-literal
 * syntax, so the substituted output is valid ESM.
 */
const HANDOFF_HELPER_TEMPLATE = `#!/usr/bin/env node
// AUTO-GENERATED by Relay. Do not edit. Per-run handoff validator.
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { resolve, sep } from 'node:path';
import { argv, exit, pid, stderr, stdin, stdout } from 'node:process';

const SCHEMAS = /*__SCHEMAS__*/;
const HANDOFFS_DIR = /*__HANDOFFS_DIR__*/;
const RUN_DIR = /*__RUN_DIR__*/;

function resolveRef(root, ref) {
  if (typeof ref !== 'string' || !ref.startsWith('#/')) return undefined;
  const parts = ref.slice(2).split('/').map((s) => s.replaceAll('~1', '/').replaceAll('~0', '~'));
  let cur = root;
  for (const seg of parts) {
    if (cur === null || typeof cur !== 'object') return undefined;
    cur = cur[seg];
  }
  return cur;
}

function jsonShape(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  if (typeof value === 'number') return Number.isInteger(value) ? 'integer' : 'number';
  return typeof value;
}

function typeMatches(want, value) {
  const shape = jsonShape(value);
  if (want === 'integer') return shape === 'integer';
  if (want === 'number') return shape === 'integer' || shape === 'number';
  return want === shape;
}

function deepEqual(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

function validate(value, schema, root, pointer) {
  if (schema === true || schema === undefined) return [];
  if (schema === false) return [{ pointer, message: 'schema rejects all values' }];
  if (typeof schema !== 'object' || schema === null) return [];

  if (typeof schema.$ref === 'string') {
    const target = resolveRef(root, schema.$ref);
    if (target === undefined) {
      return [{ pointer, message: 'unresolved $ref ' + schema.$ref }];
    }
    return validate(value, target, root, pointer);
  }

  const errors = [];

  if (schema.type !== undefined) {
    const wanted = Array.isArray(schema.type) ? schema.type : [schema.type];
    const ok = wanted.some((w) => typeMatches(w, value));
    if (!ok) {
      errors.push({
        pointer,
        message: 'expected type ' + wanted.join('|') + ', got ' + jsonShape(value),
      });
      return errors;
    }
  }

  if ('const' in schema && !deepEqual(value, schema.const)) {
    errors.push({ pointer, message: 'expected const ' + JSON.stringify(schema.const) });
  }

  if (Array.isArray(schema.enum)) {
    const matched = schema.enum.some((c) => deepEqual(c, value));
    if (!matched) {
      errors.push({
        pointer,
        message: 'expected one of ' + schema.enum.map((v) => JSON.stringify(v)).join(', '),
      });
    }
  }

  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
    if (Array.isArray(schema.required)) {
      for (const key of schema.required) {
        if (!Object.prototype.hasOwnProperty.call(value, key)) {
          errors.push({ pointer: pointer + '/' + key, message: 'required property missing' });
        }
      }
    }
    if (schema.properties && typeof schema.properties === 'object') {
      for (const [key, sub] of Object.entries(schema.properties)) {
        if (Object.prototype.hasOwnProperty.call(value, key)) {
          errors.push(...validate(value[key], sub, root, pointer + '/' + key));
        }
      }
    }
    if (schema.additionalProperties === false) {
      const known = new Set(Object.keys(schema.properties ?? {}));
      for (const key of Object.keys(value)) {
        if (!known.has(key)) {
          errors.push({
            pointer: pointer + '/' + key,
            message: 'additional property not allowed',
          });
        }
      }
    }
  }

  if (Array.isArray(value) && schema.items) {
    const itemSchema = schema.items;
    for (let i = 0; i < value.length; i += 1) {
      errors.push(...validate(value[i], itemSchema, root, pointer + '/' + i));
    }
  }

  for (const key of ['oneOf', 'anyOf']) {
    const variants = schema[key];
    if (!Array.isArray(variants)) continue;
    let matched = 0;
    let firstErrors = null;
    for (const sub of variants) {
      const errs = validate(value, sub, root, pointer);
      if (errs.length === 0) {
        matched += 1;
      } else if (firstErrors === null) {
        firstErrors = errs;
      }
    }
    if (key === 'oneOf' && matched !== 1) {
      errors.push({ pointer, message: 'expected exactly one of oneOf to match (matched ' + matched + ')' });
      if (matched === 0 && firstErrors !== null) errors.push(...firstErrors);
    }
    if (key === 'anyOf' && matched === 0) {
      errors.push({ pointer, message: 'did not match any of anyOf' });
      if (firstErrors !== null) errors.push(...firstErrors);
    }
  }

  return errors;
}

async function readStdin() {
  const chunks = [];
  for await (const chunk of stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf8');
}

function ensureInsideRun(p) {
  const root = resolve(RUN_DIR);
  const full = resolve(p);
  const prefix = root.endsWith(sep) ? root : root + sep;
  if (full !== root && !full.startsWith(prefix)) return null;
  return full;
}

function knownIds() {
  return Object.keys(SCHEMAS).join(', ');
}

function usage(message) {
  stderr.write('ERR USAGE: ' + message + '\\n');
  exit(1);
}

async function main() {
  const args = argv.slice(2);
  const cmd = args[0];

  if (cmd === undefined) usage('expected "write <id>" or "schema <id>"');

  if (cmd === 'schema') {
    const id = args[1];
    if (id === undefined) usage('schema <id>');
    const schema = SCHEMAS[id];
    if (schema === undefined) {
      stderr.write('ERR UNKNOWN_HANDOFF: "' + id + '" — known: ' + knownIds() + '\\n');
      exit(4);
    }
    stdout.write(JSON.stringify(schema, null, 2) + '\\n');
    exit(0);
  }

  if (cmd !== 'write') usage('unknown command "' + cmd + '"');

  const id = args[1];
  if (id === undefined) usage('write <id> [--from <path>]');

  let raw;
  const fromIdx = args.indexOf('--from');
  if (fromIdx !== -1) {
    const fromPath = args[fromIdx + 1];
    if (fromPath === undefined) usage('--from requires a path');
    const resolved = ensureInsideRun(fromPath);
    if (resolved === null) {
      stderr.write('ERR PATH_TRAVERSAL: "' + fromPath + '" escapes run directory\\n');
      exit(5);
    }
    try {
      raw = readFileSync(resolved, 'utf8');
    } catch (e) {
      stderr.write('ERR READ: ' + (e instanceof Error ? e.message : String(e)) + '\\n');
      exit(2);
    }
  } else {
    raw = await readStdin();
  }

  let value;
  try {
    value = JSON.parse(raw);
  } catch (e) {
    stderr.write('ERR JSON_PARSE: ' + (e instanceof Error ? e.message : String(e)) + '\\n');
    exit(2);
  }

  const schema = SCHEMAS[id];
  if (schema === undefined) {
    stderr.write('ERR UNKNOWN_HANDOFF: "' + id + '" — known: ' + knownIds() + '\\n');
    exit(4);
  }

  const errors = validate(value, schema, schema, '');
  if (errors.length > 0) {
    for (const err of errors) {
      const p = err.pointer === '' ? '/' : err.pointer;
      stderr.write('ERR SCHEMA ' + p + ': ' + err.message + '\\n');
    }
    exit(3);
  }

  try {
    mkdirSync(HANDOFFS_DIR, { recursive: true });
    const tempPath = HANDOFFS_DIR + '/' + id + '.json.tmp-' + pid + '-' + Math.random().toString(36).slice(2);
    const finalPath = HANDOFFS_DIR + '/' + id + '.json';
    writeFileSync(tempPath, JSON.stringify(value, null, 2) + '\\n');
    renameSync(tempPath, finalPath);
    stdout.write('OK ' + id + '\\n');
    exit(0);
  } catch (e) {
    stderr.write('ERR WRITE: ' + (e instanceof Error ? e.message : String(e)) + '\\n');
    exit(2);
  }
}

main().catch((e) => {
  stderr.write('ERR INTERNAL: ' + (e instanceof Error ? e.message : String(e)) + '\\n');
  exit(1);
});
`;

export interface RenderHandoffHelperArgs {
  /** Map of handoff id → JSON Schema (the output of `z.toJSONSchema`). */
  schemasById: Record<string, unknown>;
  /** Absolute path to the run directory the script lives under. */
  runDir: string;
  /** Absolute path the script should write validated handoff files into. */
  handoffsDir: string;
}

/**
 * Renders the helper script source by interpolating the schema map and
 * directory paths into the template. JSON.stringify produces output that is
 * valid both as JSON and as a JS object literal/string literal, so the
 * substitution lands in a syntactically valid ESM file without any escaping
 * gymnastics.
 */
export function renderHandoffHelperScript(args: RenderHandoffHelperArgs): string {
  return HANDOFF_HELPER_TEMPLATE.replace(
    '/*__SCHEMAS__*/',
    JSON.stringify(args.schemasById, null, 2),
  )
    .replace('/*__HANDOFFS_DIR__*/', JSON.stringify(args.handoffsDir))
    .replace('/*__RUN_DIR__*/', JSON.stringify(args.runDir));
}
