import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { writeHandoffHelperScript } from '../../src/orchestrator/handoff-helper.js';
import { renderHandoffHelperScript } from '../../src/orchestrator/handoff-helper-template.js';
import { z } from '../../src/zod.js';

const execFileAsync = promisify(execFile);

interface ExecOutcome {
  stdout: string;
  stderr: string;
  exitCode: number;
}

async function runHelper(scriptPath: string, args: string[], stdin?: string): Promise<ExecOutcome> {
  try {
    const child = execFileAsync('node', [scriptPath, ...args], {
      encoding: 'utf8',
    });
    if (stdin !== undefined) {
      child.child.stdin?.end(stdin);
    } else {
      child.child.stdin?.end();
    }
    const { stdout, stderr } = await child;
    return { stdout, stderr, exitCode: 0 };
  } catch (caught) {
    if (caught !== null && typeof caught === 'object') {
      const c = caught as { stdout?: string; stderr?: string; code?: number };
      return {
        stdout: c.stdout ?? '',
        stderr: c.stderr ?? '',
        exitCode: typeof c.code === 'number' ? c.code : 1,
      };
    }
    throw caught;
  }
}

describe('handoff-helper template renderer', () => {
  it('renders schemas, runDir, and handoffsDir into a syntactically valid ESM module', () => {
    const source = renderHandoffHelperScript({
      schemasById: { greeted: { type: 'object', properties: { name: { type: 'string' } } } },
      runDir: '/tmp/relay-run',
      handoffsDir: '/tmp/relay-run/handoffs',
    });
    expect(source).toContain('AUTO-GENERATED by Relay');
    expect(source).toContain('"greeted"');
    expect(source).toContain('"/tmp/relay-run"');
    expect(source).toContain('"/tmp/relay-run/handoffs"');
    // None of the placeholder markers should leak into the rendered output.
    expect(source).not.toContain('/*__SCHEMAS__*/');
    expect(source).not.toContain('/*__HANDOFFS_DIR__*/');
    expect(source).not.toContain('/*__RUN_DIR__*/');
  });
});

describe('handoff-helper script — spawned subprocess', () => {
  let runDir: string;
  let handoffsDir: string;
  let stagingDir: string;
  let scriptPath: string;

  const greetedSchema = z.toJSONSchema(
    z.object({ name: z.string(), tags: z.array(z.string()).optional() }),
  );
  const tallySchema = z.toJSONSchema(z.object({ count: z.number().int() }));

  beforeEach(async () => {
    runDir = await mkdtemp(join(tmpdir(), 'relay-helper-'));
    handoffsDir = join(runDir, 'handoffs');
    stagingDir = join(runDir, '.tmp');
    await mkdir(handoffsDir, { recursive: true });
    await mkdir(stagingDir, { recursive: true });
    const written = await writeHandoffHelperScript({
      runDir,
      handoffsDir,
      schemasById: {
        greeted: greetedSchema as Record<string, unknown>,
        tally: tallySchema as Record<string, unknown>,
      },
    });
    if (written.isErr()) throw written.error;
    scriptPath = written.value;
  });

  afterEach(async () => {
    await rm(runDir, { recursive: true, force: true });
  });

  it('write --from with valid JSON validates, atomically promotes, and exits 0', async () => {
    const stagingPath = join(stagingDir, 'greeted.json');
    await writeFile(stagingPath, JSON.stringify({ name: 'alice' }), 'utf8');
    const outcome = await runHelper(scriptPath, ['write', 'greeted', '--from', stagingPath]);
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout.trim()).toBe('OK greeted');
    const persisted = await readFile(join(handoffsDir, 'greeted.json'), 'utf8');
    expect(JSON.parse(persisted)).toEqual({ name: 'alice' });
  });

  it('write via stdin works the same as --from', async () => {
    const outcome = await runHelper(scriptPath, ['write', 'tally'], JSON.stringify({ count: 7 }));
    expect(outcome.exitCode).toBe(0);
    expect(outcome.stdout.trim()).toBe('OK tally');
    const persisted = await readFile(join(handoffsDir, 'tally.json'), 'utf8');
    expect(JSON.parse(persisted)).toEqual({ count: 7 });
  });

  it('JSON syntax error exits 2 with ERR JSON_PARSE on stderr', async () => {
    const outcome = await runHelper(scriptPath, ['write', 'tally'], '{not json');
    expect(outcome.exitCode).toBe(2);
    expect(outcome.stderr).toMatch(/^ERR JSON_PARSE/);
  });

  it('schema mismatch exits 3 with one ERR SCHEMA line per issue on stderr', async () => {
    const stagingPath = join(stagingDir, 'greeted.json');
    await writeFile(stagingPath, JSON.stringify({ name: 42 }), 'utf8');
    const outcome = await runHelper(scriptPath, ['write', 'greeted', '--from', stagingPath]);
    expect(outcome.exitCode).toBe(3);
    expect(outcome.stderr).toMatch(/ERR SCHEMA/);
    expect(outcome.stderr).toContain('/name');
  });

  it('unknown handoff id exits 4 with the known list on stderr', async () => {
    const stagingPath = join(stagingDir, 'mystery.json');
    await writeFile(stagingPath, '{}', 'utf8');
    const outcome = await runHelper(scriptPath, ['write', 'mystery', '--from', stagingPath]);
    expect(outcome.exitCode).toBe(4);
    expect(outcome.stderr).toMatch(/^ERR UNKNOWN_HANDOFF/);
    expect(outcome.stderr).toContain('greeted');
    expect(outcome.stderr).toContain('tally');
  });

  it('--from path outside runDir exits 5 (path traversal refused)', async () => {
    const outsideDir = await mkdtemp(join(tmpdir(), 'relay-outside-'));
    const outsidePath = join(outsideDir, 'x.json');
    await writeFile(outsidePath, JSON.stringify({ name: 'alice' }), 'utf8');
    try {
      const outcome = await runHelper(scriptPath, ['write', 'greeted', '--from', outsidePath]);
      expect(outcome.exitCode).toBe(5);
      expect(outcome.stderr).toMatch(/^ERR PATH_TRAVERSAL/);
    } finally {
      await rm(outsideDir, { recursive: true, force: true });
    }
  });

  it('schema <id> prints the embedded schema on stdout and exits 0', async () => {
    const outcome = await runHelper(scriptPath, ['schema', 'greeted']);
    expect(outcome.exitCode).toBe(0);
    expect(JSON.parse(outcome.stdout)).toEqual(greetedSchema);
  });
});
